apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rn21tr13c-go-gitops
  description: This is GitOps manifest for rn21tr13c-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: rn21tr13c-go
    janus-idp.io/tekton: rn21tr13c-go
    backstage.io/kubernetes-id: rn21tr13c-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rn21tr13c-go
