apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rn21tr13c-go
  janus-idp.io/tekton: rn21tr13c-go
  backstage.io/kubernetes-id: rn21tr13c-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rn21tr13c-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
